### ISSUE TITLE
System#syncAllMembersFromPK() throwing TypeError: this.API is not a function

### ISSUE THREAD

**Issue by chocololat** [padlocks/SimplyAPI#7]
I've been trying to use the syncing function for quite some time now, for a plugin, and i've been getting this error

```
TypeError: this.API is not a function
    at System.get (/home/runner/ouiallez/node_modules/simplyapi/lib/SimplyAPI.js:20:21)
    at System.syncAllMembersWithPluralKit (/home/runner/ouiallez/node_modules/simplyapi/lib/system.js:460:27)
    at System.syncAllMembersFromPK (/home/runner/ouiallez/node_modules/simplyapi/lib/system.js:478:51)
    at main (/home/runner/ouiallez/index.js:16:16)
    at Object.<anonymous> (/home/runner/ouiallez/index.js:18:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

I can't rely on a .env file for the config so I set the tokens manually in the code, is it why?

Here's the code

```js
const spAPI = require('simplyapi');

requestSP() {
        spAPI.SimplyAPI.set("pk_token", "pluralKitToken")
        spAPI.SimplyAPI.set("userId", "simplyPluralUserID");
        spAPI.SimplyAPI.set("token", "simplyPluralToken");
        spAPI.SimplyAPI.set("header", {
            'Content-Type': 'application/json',
            'Authorization': "simplyPluralToken")
        })

        console.log(spAPI.SimplyAPI.API()); //works, console logging the object

        let system = new spAPI.System(spAPI.Config)

        system.syncAllMembersFromPK(); // TypeError: this.API is not a function
    }
    
requestSP();
```

**Comment by padlocks** [comment]
Thanks for reporting!! I'll get a fix out shortly.
